from __future__ import annotations

import json
from pathlib import Path
from typing import Optional


_FIXTURE_ROOT = Path(__file__).resolve().parents[2] / 'Fixtures' / 'PipelineFiles'


# directive: e2e-pipeline-test-framework
class FixtureMissingError(RuntimeError):
    """Permanent fixture file or properties.json missing -- run RegenerateFromLive.py."""


# directive: e2e-pipeline-test-framework
def _BucketDir(Bucket: str) -> Path:
    Allowed = {'Transcode', 'Remux', 'AudioFixOnly', 'Compliant'}
    if Bucket not in Allowed:
        raise ValueError(f"Bucket must be one of {sorted(Allowed)}; got {Bucket!r}")
    return _FIXTURE_ROOT / Bucket


# directive: e2e-pipeline-test-framework
def GetProperties(Bucket: str) -> dict:
    """Load the per-bucket properties.json. Raises FixtureMissingError if absent."""
    Path_ = _BucketDir(Bucket) / 'properties.json'
    if not Path_.exists():
        raise FixtureMissingError(f"Missing {Path_}. Run: py Tests/Fixtures/PipelineFiles/RegenerateFromLive.py")
    return json.loads(Path_.read_text(encoding='utf-8'))


# directive: e2e-pipeline-test-framework
def GetFixtureFile(Bucket: str) -> Path:
    """Return the local Path to the fixture binary. Verifies the file actually exists on disk."""
    Props = GetProperties(Bucket)
    LocalPath = Path(Props['FixtureLocalPath'])
    if not LocalPath.exists():
        raise FixtureMissingError(
            f"Properties.json points at {LocalPath} but file is missing. Run: py Tests/Fixtures/PipelineFiles/RegenerateFromLive.py"
        )
    return LocalPath


# directive: e2e-pipeline-test-framework
def IsAvailable(Bucket: str) -> bool:
    """True when both properties.json and the binary file exist on disk."""
    try:
        GetFixtureFile(Bucket)
        return True
    except FixtureMissingError:
        return False


# directive: e2e-pipeline-test-framework
def ManifestPath() -> Path:
    return _FIXTURE_ROOT / 'manifest.json'


# directive: e2e-pipeline-test-framework
def LoadManifest() -> Optional[dict]:
    """Return the top-level manifest.json (generated by RegenerateFromLive), or None if absent."""
    P = ManifestPath()
    if not P.exists():
        return None
    return json.loads(P.read_text(encoding='utf-8'))
